/** Length-balanced option rewrites for the `rxjs` category.
 * Skips already-balanced #12/#32/#83. Answer indices unchanged (#9 stays 0,
 * #11 stays 2, #92 stays 0; the rest stay 1). Depth stays in each (untouched)
 * explanation. Backtick strings — no option contains a backtick or ${ . */
export default {
  9: { answer: 0, options: [
    `map() transforms synchronously; switchMap() cancels stale ones`,
    `map() is for filtering streams; switchMap() is for transforming`,
    `They are aliases for the same operator, just with different names`,
    `switchMap() works only with Observables; map() with any iterable`,
  ] },
  10: { answer: 1, options: [
    `signal() cannot be modified inside a subscribe callback at all`,
    `The subscription is never unsubscribed; it leaks after destroy`,
    `users$ must be piped through async before subscribing in TS`,
    `ngOnInit cannot hold manual subscriptions; use async/await`,
  ] },
  11: { answer: 2, options: [
    `mergeMap — runs all requests concurrently and emits every result`,
    `concatMap — queues the requests sequentially for guaranteed order`,
    `switchMap — cancels the previous request and switches to the new`,
    `exhaustMap — ignores new requests while one is still in flight`,
  ] },
  33: { answer: 1, options: [
    `They are interchangeable — just different names for one operator`,
    `combineLatest emits on any change; zip pairs values by index`,
    `zip() is for arrays only; combineLatest() is for Observables`,
    `combineLatest is deprecated; zip is the modern replacement`,
  ] },
  34: { answer: 1, options: [
    `interval() must be created outside of the component class`,
    `Never cleaned up; the interval keeps firing after destroy`,
    `switchMap() is the wrong operator for interval-based polling`,
    `ngOnInit cannot hold manual subscriptions; use the async pipe`,
  ] },
  81: { answer: 1, options: [
    `share() replays the last value to late subscribers; shareReplay does not`,
    `shareReplay(1) replays the last value to new subscribers; share does not`,
    `They are identical — shareReplay is just an alias with a buffer`,
    `share() refcounts automatically; shareReplay keeps the source alive`,
  ] },
  82: { answer: 1, options: [
    `of(null) completes the stream; EMPTY throws a brand-new error`,
    `of(null) emits one null then completes; EMPTY emits nothing`,
    `EMPTY emits undefined; of(null) emits null — effectively the same`,
    `of(null) retries the source; EMPTY cancels the subscription`,
  ] },
  84: { answer: 1, options: [
    `It scans the source for a value and filters non-matching ones`,
    `It accumulates like Array.reduce but emits each running result`,
    `It buffers all emissions and emits them as one array at the end`,
    `It is identical to reduce() but works on hot Observables`,
  ] },
  85: { answer: 1, options: [
    `throttleTime waits 1s after the last event; debounceTime every 1s`,
    `debounceTime emits after 1s of silence; throttleTime emits first`,
    `They are identical — use whichever one is already imported`,
    `throttleTime is deprecated; you should always use debounceTime`,
  ] },
  86: { answer: 1, options: [
    `Observable.interval(500) — the static creation helper method`,
    `interval(500) from "rxjs" — emits 0, 1, 2... every 500ms`,
    `timer(500) from "rxjs" — the recurring timer creator`,
    `fromEvent(window, "timer", 500) — a timer DOM event`,
  ] },
  87: { answer: 1, options: [
    `It merges a$ and b$ so the two run fully in parallel`,
    `When a$ emits, it grabs b$'s latest and pairs them as a tuple`,
    `It replaces each a$ emission with the latest b$ value`,
    `It subscribes to b$ first and waits for it to complete before a$`,
  ] },
  88: { answer: 1, options: [
    `It delays the subscription to observable$ by one microtask`,
    `It runs the factory fresh for each subscriber, making it lazy`,
    `It stores the Observable reference and replays it on subscribe`,
    `It is equivalent to shareReplay(1) but without any caching`,
  ] },
  89: { answer: 1, options: [
    `Store the subscription and call unsubscribe() in ngOnDestroy`,
    `Use takeUntilDestroyed(this.destroyRef); it auto-completes`,
    `Always use the async pipe so Angular manages the lifecycle`,
    `Use take(1) so the Observable completes after one emission`,
  ] },
  90: { answer: 1, options: [
    `It emits values in pairs, waiting for two then resetting`,
    `It emits [prev, curr] for every emission after the first`,
    `It combines two Observables into pairs, exactly like zip()`,
    `It is functionally identical to bufferCount(2) in every case`,
  ] },
  91: { answer: 1, options: [
    `HttpClient simply cannot be used inside service constructors`,
    `http.get() is cold; nothing subscribes, so no request fires`,
    `The request fires but the response is lost with no subscriber`,
    `Angular retries the request automatically if it fails once`,
  ] },
  92: { answer: 0, options: [
    `first() throws EmptyError on no emit; take(1) stays silent`,
    `take(1) waits for completion; first() unsubscribes after one`,
    `first() applies only to BehaviorSubject; take(1) to any source`,
    `They are completely identical in every possible case`,
  ] },
  93: { answer: 1, options: [
    `retry() must always be placed after catchError() in the pipe`,
    `retry(3) retries on ANY error, even a 404; filter to transient`,
    `catchError is not allowed to re-throw an error; return EMPTY instead`,
    `The subscription is GC'd because no reference is stored`,
  ] },
  94: { answer: 1, options: [
    `It stops combineLatest subscribing until both a$ and b$ emit`,
    `combineLatest emits once all have; the filter drops null states`,
    `filter() forces emission only when BOTH streams change together`,
    `It converts a hot combineLatest into a cold Observable`,
  ] },
  95: { answer: 1, options: [
    `It subscribes to both of them and then emits from whichever is first`,
    `It checks the condition lazily at subscription, per subscriber`,
    `It creates a conditional merge based on each emitted value`,
    `iif() is now deprecated — use a plain ternary of observables`,
  ] },
  155: { answer: 1, options: [
    `It merges the sources and emits every value as they each arrive`,
    `It waits for ALL to complete, then emits their last values`,
    `It subscribes to a$, then b$, then c$ strictly sequentially`,
    `It emits the first value from whichever emits first, then stops`,
  ] },
  163: { answer: 1, options: [
    `The mergeMap operator simply cannot be used together with HttpClient`,
    `mergeMap runs concurrently, so stale results can win; use switchMap`,
    `valueChanges does not emit on the initial control value`,
    `mergeMap requires a resultSelector second argument`,
  ] },
  170: { answer: 1, options: [
    `exhaustMap cancels the current inner when a new value arrives`,
    `exhaustMap ignores new values while an inner is active`,
    `exhaustMap is identical to concatMap but runs in parallel`,
    `exhaustMap subscribes to all inners, emitting whichever is first`,
  ] },
  176: { answer: 1, options: [
    `2, 4, 6 (once) — the result is shared between both subscribers`,
    `2, 4, 6, 2, 4, 6 — each subscription re-runs the cold source`,
    `An error — you cannot subscribe to an Observable more than once`,
    `2, 2, 4, 4, 6, 6 — the values interleave between subscribers`,
  ] },
  184: { answer: 1, options: [
    `It makes template expressions run async so they never block render`,
    `It subscribes in the template and auto-unsubscribes on destroy`,
    `It converts a Promise to an Observable before template use`,
    `It is required to use async/await inside component methods`,
  ] },
  192: { answer: 1, options: [
    `They are identical — ReplaySubject(1) is a BehaviorSubject alias`,
    `Both replay the last value, but ReplaySubject(1) starts empty`,
    `ReplaySubject(1) emits asynchronously; BehaviorSubject is sync`,
    `ReplaySubject replays to all; BehaviorSubject only to new ones`,
  ] },
  206: { answer: 1, options: [
    `6 — like reduce, only the final total is ever emitted`,
    `1, 3, 6 — scan emits the running accumulator after each value`,
    `0, 1, 3, 6 — the seed value is emitted first, then all the rest`,
    `1, 2, 3 — scan passes the values straight through unchanged`,
  ] },
  207: { answer: 1, options: [
    `It buffers every emission forever; cap it with take(1)`,
    `The source stays subscribed after all unsub; use refCount: true`,
    `shareReplay makes a new subscription per subscriber; use share()`,
    `It only works inside components; move it to a service to fix`,
  ] },
  208: { answer: 1, options: [
    `The debounceTime must be placed only after switchMap in the pipe`,
    `catchError sits on the OUTER stream; move it inside switchMap`,
    `switchMap should be mergeMap so requests are not cancelled`,
    `of([]) is wrong; catchError must rethrow to keep it alive`,
  ] },
  209: { answer: 1, options: [
    `{ user: {id:1}, ticks: 0 } after one second, then done`,
    `Nothing — forkJoin needs all to complete; interval never does`,
    `{ user: {id:1} } immediately, ignoring the pending ticks`,
    `It errors because you cannot mix finite and infinite sources`,
  ] },
  224: { answer: 1, options: [
    `Anywhere — it always finds the current component for you`,
    `Only in an injection context; else pass the DestroyRef in`,
    `Only inside ngOnDestroy, after the component is torn down`,
    `Only in services, and never inside any component at all`,
  ] },
  257: { answer: 1, options: [
    `a2b2 — only the final combination is ever logged`,
    `a1b1, a2b1, a2b2 — emits initially, then on each change`,
    `a1b1, a2b2 — only when both change together simultaneously`,
    `a1b1 — combineLatest emits just once and then completes`,
  ] },
  258: { answer: 1, options: [
    `2, 3, 1 — the one delayed value ends up arriving last of all`,
    `1, 2, 3 — concatMap runs each inner fully before the next`,
    `3, 2, 1 — the values come out in reverse order`,
    `1, 2, 3 emitted all at once with no delay honored`,
  ] },
  259: { answer: 1, options: [
    `1, 2, 3 — every duplicate value is removed globally here`,
    `1, 2, 3, 1 — only CONSECUTIVE duplicates are suppressed`,
    `1, 1, 2, 2, 3, 1 — nothing at all is filtered out`,
    `1 — the stream stops at the very first repeat`,
  ] },
  260: { answer: 1, options: [
    `2, 4, 6, 8 — all even numbers, just skipping the odd 7`,
    `2, 4, 6 — takeWhile completes at the first failing value (7)`,
    `2, 4, 6, 7 — the failing value is emitted just before it stops`,
    `2 — the stream stops right after the very first value`,
  ] },
  261: { answer: 1, options: [
    `0, 5, 9 — every single count change is logged as it happens`,
    `5 — emits only on clicks$, pairing count's latest (5)`,
    `5, 9 — both of the counts after the click occurs`,
    `nothing — clicks$ never carries a value to log`,
  ] },
  288: { answer: 1, options: [
    `1, 2, 3 — every value passes through untouched`,
    `1, 99 — throws on 2, catchError yields 99, then completes`,
    `1, 2, 99, 3 — the error is caught and yet 3 still emits after`,
    `99 only — the whole stream is replaced from the start`,
  ] },
  289: { answer: 1, options: [
    `It caches the successful response for roughly 3 whole seconds`,
    `On error it re-requests up to 3 times, 1000ms apart`,
    `It fires the same request three times in parallel`,
    `It retries only on 4xx client errors, nothing else`,
  ] },
  290: { answer: 1, options: [
    `It selects which operator in the pipe runs next`,
    `It controls WHEN and in what context emissions are delivered`,
    `It is required for every observable to emit any value at all`,
    `It only ever affects how errors are handled in a stream`,
  ] },
  291: { answer: 1, options: [
    `EMPTY throws synchronously the moment it is returned`,
    `catchError returns EMPTY, which completes without erroring`,
    `The object-form subscribe observer syntax is invalid here`,
    `HttpClient errors simply cannot be caught by catchError at all`,
  ] },
  292: { answer: 1, options: [
    `Only when the observable actually emits a value downstream`,
    `Once on termination — complete, error, OR unsubscription`,
    `Immediately, just before the very first emission happens`,
    `Only on successful completion, and never ever on an error`,
  ] },
};
