/** Length-balanced option rewrites for the `signals` category.
 * Skips already-balanced #5/#73/#74. Answer indices unchanged from current data
 * (#7 stays 0, #69 stays 0, #71 stays 2, #77 stays 0; all others stay 1). Depth
 * lives in each (untouched) explanation. Backtick strings — no option contains a
 * backtick or ${ . */
export default {
  6: { answer: 1, options: [
    `computed() cannot be a const; use let with an explicit generic type`,
    `price and tax are signals — call them to read: price() + tax()`,
    `A numeric signal and a decimal signal cannot be added due to typing`,
    `computed() must return an Observable, not a plain numeric value here`,
  ] },
  7: { answer: 0, options: [
    `computed() is lazy and memoized (a Signal); effect() runs side effects`,
    `They behave identically; effect() is just the async form recommended here`,
    `computed() works only in templates; effect() only in services/components`,
    `effect() returns a writable signal; computed() returns a read-only one`,
  ] },
  8: { answer: 1, options: [
    `signal() cannot be used inside services; use a BehaviorSubject instead`,
    `items is a public writable signal; keep it private, expose asReadonly()`,
    `computed() may not reference other signals from its own store class here`,
    `Stateful services must extend the NgRx StoreModule or add lifecycle hooks`,
  ] },
  29: { answer: 1, options: [
    `The Observable is eagerly subscribed well before the component renders`,
    `Type is Signal<T[]>, not Signal<T[] | undefined>; value exists at once`,
    `The signal auto-unsubscribes immediately after its very first emission`,
    `The Observable is shared via multicasting across every one of the subscribers`,
  ] },
  30: { answer: 1, options: [
    `effect() is not allowed to be created inside a component constructor`,
    `Reading then setting count() in one effect makes an infinite cycle`,
    `You must use computed() instead for any kind of numeric state derivation`,
    `effect() cannot call signal.set(); only read-only operations are allowed`,
  ] },
  31: { answer: 1, options: [
    `linkedSignal() forges a permanent, unbreakable link between two signals`,
    `linkedSignal() is writable — defaults to the derived value but takes .set()`,
    `linkedSignal() is the signal-world equivalent of RxJS shareReplay(1)`,
    `linkedSignal() converts a signal into an Observable stream automatically for you`,
  ] },
  66: { answer: 1, options: [
    `http.get() is simply not allowed to be called inside of an effect`,
    `The .subscribe() is never cleaned up, so rapid changes stack subscriptions`,
    `this.user.set() is simply not allowed to be called inside of an effect`,
    `effect() re-runs synchronously on every single change-detection cycle here`,
  ] },
  67: { answer: 1, options: [
    `The signal will only ever store arrays — the equal function is a type guard`,
    `Same-length arrays are treated as equal, so consumers are not notified`,
    `The signal throws whenever you set an array of a different length than before`,
    `It switches on deep structural equality checking for the nested array items`,
  ] },
  68: { answer: 1, options: [
    `A Promise that resolves once to the signal's current value on read`,
    `An Observable that emits the value now, then on every later change`,
    `A Subject you must manually push the signal's values into yourself`,
    `An Observable that emits once with the final value on component destroy`,
  ] },
  69: { answer: 0, options: [
    `The read is not tracked as a dependency, so the context will not re-run`,
    `It logs the signal read to the Angular DevTools without a dependency`,
    `It takes a one-time snapshot of the value that then never updates again`,
    `It throws if used inside a computed — it is valid only within effects`,
  ] },
  70: { answer: 1, options: [
    `Export one global signal object and mutate it freely from any component`,
    `Private writable signals, public readonly/asReadonly, named mutators`,
    `Keep state in a BehaviorSubject and pipe it to a signal in each component`,
    `Store all of the state in the router query params so it syncs to the URL`,
  ] },
  71: { answer: 2, options: [
    `Just three: "loading", "loaded", and "error"`,
    `"idle", "loading", "resolved", "error", "refreshing" — five string values`,
    `Idle, Loading, Resolved, Error, Refreshing (the ResourceStatus enum)`,
    `Just three: "pending", "complete", and "failed"`,
  ] },
  72: { answer: 1, options: [
    `rxResource() is always faster, so you should just prefer it every time`,
    `When the loader returns an Observable (HttpClient) instead of a Promise`,
    `rxResource() caches its results permanently; resource() never caches at all`,
    `rxResource() works under SSR while resource() is strictly browser-only`,
  ] },
  75: { answer: 1, options: [
    `It chains two signals so setting one sets the other, bidirectionally`,
    `A writable signal that resets to a derived value when its source changes`,
    `A performance-tuned variant of computed() for deeply nested object trees`,
    `It links a signal to an Observable stream so it updates automatically here`,
  ] },
  76: { answer: 1, options: [
    `A plain array holding the matching ItemComponent instances in the view`,
    `A Signal<ReadonlyArray<ItemComponent>> that updates as children change`,
    `A QueryList<ItemComponent> that emits whenever the children change here`,
    `One ItemComponent instance — use viewChildren for the plural form here`,
  ] },
  77: { answer: 0, options: [
    `Signals are synchronous and type-safe; FormControl is Observable-based`,
    `FormControl renders faster; signal() is the faster option for services`,
    `Signals cannot hold complex objects; FormControl is built for nested data`,
    `They are equivalent — Angular converts signals to FormControls for you`,
  ] },
  78: { answer: 1, options: [
    `computed() flatly does not allow any conditional logic inside its body`,
    `A throw marks the computed errored and re-throws to every reader of it`,
    `The error is swallowed silently, so result() simply returns undefined`,
    `computed() catches the thrown error for you and returns null in its place`,
  ] },
  79: { answer: 1, options: [
    `Simply call fixture.detectChanges() a second consecutive time`,
    `Use TestBed.flushEffects() (or tick() in fakeAsync); they are async`,
    `Effects flush automatically once you read a signal — no test code needed`,
    `Wrap the assertion in a setTimeout(() => { ... }, 0) callback instead`,
  ] },
  80: { answer: 1, options: [
    `Calling set() inside any effect is simply not allowed by the framework`,
    `It syncs one signal to another via a side effect — use computed() instead`,
    `The effect will throw because doing this creates a real dependency cycle here`,
    `Effects that call set() were formally deprecated back in Angular 18+`,
  ] },
  153: { answer: 1, options: [
    `Angular always notifies dependents, even when the value is unchanged`,
    `By default Object.is() equality skips notifying dependents on equal values`,
    `Angular immediately throws a "duplicate set" error at you in this case`,
    `The signal's internal version counter still increments even on the equal values`,
  ] },
  162: { answer: 1, options: [
    `effect() is for synchronous logic while computed() is meant for async`,
    `computed() derives a lazy signal value; effect() runs side effects only`,
    `effect() re-runs each change-detection cycle; computed() only when read`,
    `They are interchangeable — just use whichever one happens to read cleaner`,
  ] },
  169: { answer: 1, options: [
    `toSignal() converts a Promise to a signal; it cannot handle Observables`,
    `Wraps an Observable as a read-only signal; needs an injection context`,
    `toSignal() sets up a two-way binding between an Observable and a signal`,
    `toSignal() behaves just like takeUntilDestroyed — it only handles cleanup`,
  ] },
  172: { answer: 1, options: [
    `update() triggers change detection whereas set() does not do so at all`,
    `set(value) replaces it; update(fn) maps the current value to a new one`,
    `update() is meant for objects while set() is meant only for primitives`,
    `They are identical — update(fn) is just shorthand for set(fn(signal()))`,
  ] },
  179: { answer: 1, options: [
    `The phases control which components in the tree get to render first`,
    `Four ordered phases (read/write) run reads after writes, avoiding thrash`,
    `The phases are used by the Angular animations engine to sequence work`,
    `The afterRender phases only ever apply within server-side rendering here`,
  ] },
  189: { answer: 1, options: [
    `resource() caches responses forever; Observable subscriptions do not`,
    `It ties async loading to signals: auto re-fetch, status, and cancellation`,
    `resource() is only for HTTP; Observables can work with any async source here`,
    `resource() is faster because it uses the Fetch API instead of HttpClient`,
  ] },
  199: { answer: 1, options: [
    `No — signals inside @if blocks never update because the block may not run`,
    `Yes — the compiler tracks signal reads in @if, @for and @switch blocks`,
    `Only if you manually call detectChanges() after each and every update`,
    `Yes, but only for OnPush components; default detection ignores the reads`,
  ] },
  201: { answer: 1, options: [
    `22 — count re-runs and reads both the new a (2) and the new b (20)`,
    `12 — it last ran on a.set(2) with untracked b=10; b.set does not invalidate`,
    `11 — the initial value, because untracked entirely freezes the computed in place`,
    `21 — a stays at 1 the whole time while b updates its value to 20`,
  ] },
  202: { answer: 1, options: [
    `It runs a single time on component destroy, exactly like ngOnDestroy`,
    `Teardown that runs before the effect's next run and on its destruction`,
    `It cancels the effect permanently right after its very first execution`,
    `onCleanup is not a real API — effects simply never need manual cleanup`,
  ] },
  203: { answer: 1, options: [
    `It runs once at creation only to validate the initial value's type`,
    `Called with (prev, next) per write; returning true means "not changed"`,
    `It deep-clones the value before storing it so as to guarantee immutability`,
    `It turns the signal into a computed by deriving equality from others`,
  ] },
  223: { answer: 1, options: [
    `Nothing — it is honestly just a shorter syntax for the same behavior`,
    `Reactive re-fetch on request change, value/status/error signals, abort`,
    `It caches every one of the results permanently and then never refetches`,
    `It converts an Observable into a Promise for you behind the scenes here`,
  ] },
  244: { answer: 1, options: [
    `The signal() call is wrong — it should be signal({ value: 0 }) instead`,
    `A signal is a getter function — you must call it in the template: count()`,
    `You forgot to import CommonModule, which is required in order to display signals`,
    `The signal has to be marked readonly before it is allowed to render out`,
  ] },
  262: { answer: 1, options: [
    `'b' — the manual override that the user set sticks around permanently`,
    `'x' — linkedSignal resets to its derived value when the source changes`,
    `'a' — it always returns the original first option no matter what happens`,
    `'y' — it takes the last element of the array rather than the first one`,
  ] },
  263: { answer: 1, options: [
    `(1) 2 then (2) 6 2 — the computed recomputes once on each set() call`,
    `(1) 0 then (2) 6 1 — computed is lazy and memoized; sets collapse into one`,
    `(1) 0 then (2) 6 3 — it runs once for every set() plus once more for the read`,
    `(1) 1 then (2) 6 1 — it runs eagerly a single time at creation of it`,
  ] },
  264: { answer: 1, options: [
    `Three times: it logs run 0, then run 1, and finally run 2 in order`,
    `Once: run 2 — effects run async and coalesce the synchronous writes`,
    `Twice: it logs run 0 first, and then it logs run 2 afterwards here`,
    `Never: effects need a change-detection pass to run and none happens`,
  ] },
  345: { answer: 1, options: [
    `computed() — simply derive the current selection straight from the list`,
    `linkedSignal(() => options()[0]) — writable, re-derives when source changes`,
    `An effect() that watches the list and then calls selection.set() when it moves`,
    `A plain signal plus a manual subscription kept in sync with the list here`,
  ] },
  346: { answer: 1, options: [
    `"computing" three times (once per value), and then it prints 6, 6`,
    `"computing" once, then 6, then 6 — computed is lazy and memoized here`,
    `"computing", 6, "computing", 6 — every single read recomputes the body`,
    `"computing", 2, then 6, 6 — the intermediate value 2 prints in between`,
  ] },
  347: { answer: 1, options: [
    `effect() cannot read signals at all — it must take them as arguments`,
    `Derived state via an effect: total should be a computed(), not a write`,
    `reduce() is simply not allowed to be used inside any reactive context`,
    `The effect must be wrapped in untracked() to avoid an infinite loop here`,
  ] },
  348: { answer: 1, options: [
    `@for is fundamentally unable to iterate over the values held in a signal`,
    `The array is mutated in place with push(); no set()/update() ever fires`,
    `The track expression has to be $index whenever you use string arrays`,
    `signal<string[]> is invalid syntax; arrays require the signal.array() form`,
  ] },
  349: { answer: 1, options: [
    `toSignal waits for the first template read before it ever subscribes`,
    `It subscribes at once, needs an injection context, reads undefined early`,
    `It throws an error at you unless the source observable actually completes`,
    `It re-subscribes to the source observable again on every single read`,
  ] },
  350: { answer: 1, options: [
    `signal.required for the first blank and coerce for the second blank`,
    `input.required for the first blank and transform for the second blank`,
    `@Input({ required }) for the first blank and map for the second blank`,
    `input.mandatory for the first blank and parse for the second blank here`,
  ] },
  351: { answer: 1, options: [
    `Nothing real — it is only a bit of syntax sugar around subscribe()`,
    `Signal-native async: tracked params, request abort, status/value signals`,
    `It caches every single one of the responses into localStorage for you`,
    `It makes HTTP calls fully synchronous so templates never need loading states`,
  ] },
  352: { answer: 1, options: [
    `Wrap the downstream computed body in untracked() so it stops updating`,
    `Give the signal a custom equal that compares fields, not object identity`,
    `Debounce the keystrokes instead, since equality simply cannot be tuned`,
    `Convert the object to a JSON string signal so the comparison works right`,
  ] },
};
