/** Length-balanced option rewrites for the `testing` category.
 * Skips already-balanced #18/#122. Every answer index stays 1 (matches current
 * data). Depth lives in each (untouched) explanation. Backtick strings — no
 * option contains a backtick or ${ . */
export default {
  17: { answer: 1, options: [
    `It closes the HTTP connection and so it prevents any port exhaustion here`,
    `It asserts every expected request was flushed; unhandled ones then fail`,
    `It resets the component and the service state in between the test runs`,
    `It is optional for GET requests but is required for POST and PUT ones`,
  ] },
  40: { answer: 1, options: [
    `It runs the tests in parallel across several separate OS-level threads`,
    `Control time synchronously via tick(ms) and flushMicrotasks() calls`,
    `It lets you skip all of the async setup done inside the beforeEach block`,
    `Mock the HTTP requests entirely without any HttpTestingController at all`,
  ] },
  41: { answer: 1, options: [
    `querySelector will always return null when you are inside a unit test`,
    `fixture.detectChanges() was never called, so the DOM never re-rendered`,
    `The component.user field should really be set via a signal instead here`,
    `toContain should have been toBe for doing an exact text-match comparison`,
  ] },
  42: { answer: 1, options: [
    `Harnesses run about ten times faster than the raw DOM queries do here`,
    `They expose a semantic API (click, getValue) so tests survive refactors`,
    `Harnesses will only ever work with the Angular Material components here`,
    `Harnesses automatically add all of the needed accessibility attributes`,
  ] },
  121: { answer: 1, options: [
    `A brand-new instance of MyService built outside of Angular's DI system`,
    `The same DI singleton the tested components receive from the injector`,
    `A Jasmine or a Jest generated mock stand-in of the real MyService class`,
    `It throws — services must be reached only through the component fixture`,
  ] },
  123: { answer: 1, options: [
    `nativeElement.click() is always best for accuracy; the other is legacy`,
    `click() fires real bubbling browser events; the other fires the binding`,
    `triggerEventHandler only works with (click); nativeElement.click() any event`,
    `They are entirely identical when running in a jsdom test environment here`,
  ] },
  124: { answer: 1, options: [
    `To reset the underlying HTTP client cleanly in between the tests here`,
    `To assert no unexpected requests remain; leftovers contaminate the next`,
    `To flush every one of the pending requests with an automatic 200 OK here`,
    `verify() is only ever needed when you are testing the error scenarios`,
  ] },
  125: { answer: 1, options: [
    `Import RouterModule and then inspect the window.location.href value here`,
    `Spy on router.navigate and assert toHaveBeenCalledWith(["/home"]) on it`,
    `Use fakeAsync with a tick() call to flush the pending navigation here`,
    `Call fixture.detectChanges() and check the DOM for a router-outlet change`,
  ] },
  126: { answer: 1, options: [
    `createComponent() must be called inside beforeEach(), never inside it()`,
    `detectChanges() is never called, so the template has not rendered yet`,
    `textContent returns an array within jsdom rather than an ordinary string`,
    `The component must implement OnInit for its textContent to be populated`,
  ] },
  127: { answer: 1, options: [
    `It prevents every kind of error message from showing in the test output`,
    `It tells Angular to ignore unknown elements/attributes — a shallow render`,
    `It disables all of the form validation for the whole duration of the test`,
    `It makes every HTTP error return a 200 OK instead of actually throwing`,
  ] },
  128: { answer: 1, options: [
    `Configure a full TestBed with the pipe declared and test via a fixture`,
    `Instantiate it with new MyPipe() and call transform() — no TestBed needed`,
    `Use Jasmine's createSpy() to mock out the pipe's own transform method`,
    `Pipes cannot be unit tested — only integration tested via a host component`,
  ] },
  129: { answer: 1, options: [
    `Use HttpClientTestingModule and then flush the requests in the normal way here`,
    `Provide a test loader, or use provideHttpClientTesting() and flush the HTTP`,
    `resource() cannot be tested — just mock the service that wraps it instead`,
    `Wrap the whole test in fakeAsync() and tick() to wait for it to resolve`,
  ] },
  130: { answer: 1, options: [
    `whenStable() is faster only because it does not use any fake timers here`,
    `whenStable() resolves when async tasks finish; it works without fakeAsync`,
    `whenStable() also flushes the HTTP requests, whereas tick() does not do so`,
    `They are interchangeable — just choose based on your own team preference`,
  ] },
  131: { answer: 1, options: [
    `import { AuthService }; const mock = {}; with no DI wiring needed at all`,
    `providers: [{ provide: AuthService, useValue: mockAuthService }] does it`,
    `TestBed.configureTestingModule({ declarations: [AuthService] }) does it`,
    `Override AuthService globally by using jest.mock("./auth.service") instead`,
  ] },
  132: { answer: 1, options: [
    `flush() is simply the faster one, while tick() is the more accurate one`,
    `tick(500) advances exactly 500ms; flush() drains all pending macro-tasks`,
    `flush() only flushes the Promises; tick() flushes both Promises and timers`,
    `They are identical — flush() is just shorthand for tick(MAX_SAFE_INTEGER)`,
  ] },
  158: { answer: 1, options: [
    `Spectator's detectChanges() also flushes all pending Promises for you here`,
    `They are equivalent — Spectator just wraps TestBed with a nicer API here`,
    `Spectator's detectChanges() runs every one of the effects synchronously`,
    `fixture's only works in fakeAsync zones; Spectator's version works anywhere`,
  ] },
  171: { answer: 1, options: [
    `A spy is a mock HTTP server created via the HttpClientTestingModule here`,
    `A wrapper recording calls without real logic; made with spyOn/createSpy`,
    `A spy is used only for Angular routing — it intercepts router.navigate calls`,
    `A spy is a TypeScript partial interface that satisfies the type checker`,
  ] },
  178: { answer: 1, options: [
    `It provides a real HTTP client that makes actual requests to a test server`,
    `It replaces HttpClient with a mock you flush via HttpTestingController`,
    `It validates that all of the HTTP URLs in your app are actually reachable`,
    `It is just a thin test wrapper for the fetch API, not Angular's HttpClient`,
  ] },
  185: { answer: 1, options: [
    `It is a CSS methodology used for structuring Angular component styling`,
    `Arrange, Act, Assert — set up, act, then verify; keeps tests readable`,
    `It is the name of Angular's own three-phase change-detection cycle here`,
    `It refers to Angular's Accessibility, Animation and API testing strategy`,
  ] },
  218: { answer: 1, options: [
    `detectChanges() simply has to be called twice, one right after the other`,
    `Async work has not resolved; await whenStable() before re-checking DOM`,
    `querySelector really ought to be used here in place of textContent access`,
    `ngOnInit cannot start async work at all — move that work to the constructor`,
  ] },
  219: { answer: 1, options: [
    `imports: [HttpClient] and inject HttpClient directly to make real requests`,
    `providers: [provideHttpClient(), provideHttpClientTesting()], then inject`,
    `imports: [HttpClientModule] and then just spyOn(window, "fetch") for it`,
    `No setup at all is needed; HttpClient is auto-mocked for you in TestBed`,
  ] },
  232: { answer: 1, options: [
    `They are simply identical aliases for one another in the fakeAsync zone`,
    `tick(1000) advances exactly 1000ms; flush() drains ALL pending macrotasks`,
    `tick() handles the Promises while flush() handles only the timers instead`,
    `flush() advances a fixed 1000ms while tick() advances just 1ms at a time`,
  ] },
  233: { answer: 1, options: [
    `tick() simply must be replaced with a flush() call to clear periodic timers`,
    `setInterval leaves a periodic task queued; call discardPeriodicTasks/stop`,
    `fakeAsync cannot be used with setInterval at all — use a real async test`,
    `The interval needs to be created inside of the tick() callback instead here`,
  ] },
  234: { answer: 1, options: [
    `A way to run your Observables on a background thread purely for the speed`,
    `ASCII marble diagrams describe timed emissions; assert them synchronously`,
    `It gives you automatic mocking of all of the HttpClient requests for free`,
    `A replacement for fakeAsync that happens to only ever work with Promises`,
  ] },
  235: { answer: 1, options: [
    `Harnesses render the components about ten times faster than queries do`,
    `A semantic API (click, getText, isDisabled) so tests survive DOM refactors`,
    `Harnesses only ever exist for the sole purpose of testing forms in Angular`,
    `Harnesses remove the need to ever call fixture.detectChanges() entirely`,
  ] },
  236: { answer: 1, options: [
    `new UserService() is actually a plain syntax error when inside a spec file here`,
    `inject resolves via DI, wiring deps and overrides, returning the singleton`,
    `TestBed.inject creates a fresh instance per call, which is what you want`,
    `They are equivalent; TestBed.inject just happens to be a bit shorter here`,
  ] },
  237: { answer: 1, options: [
    `Reassign it: component["userService"] = fake after the component is built`,
    `Register it: providers: [{ provide: UserService, useValue: fake }] in DI`,
    `Just import the fake instead of the real service inside of the spec file`,
    `Fakes are not actually supported at all; you must hit the real backend here`,
  ] },
  353: { answer: 1, options: [
    `declarations: [UserCard] — exactly the same as the NgModule components`,
    `imports: [UserCard]; swap a child via TestBed.overrideComponent imports`,
    `They cannot be TestBed-tested at all; only constructor unit tests work here`,
    `providers: [UserCard] — standalone components are treated as injectables`,
  ] },
  354: { answer: 1, options: [
    `"none" then "none" — the timers just never fire inside a fakeAsync zone`,
    `"first" then "second" — tick(2000) runs the 1s timer; flush() the 3s one`,
    `"first" then "first" — because flush() only ever flushes the microtasks`,
    `It throws: you are not allowed to mix tick() and flush() in one test here`,
  ] },
  355: { answer: 1, options: [
    `expectOne needs the full absolute URL, including the host, to match here`,
    `Nobody subscribed — http.get() is cold, so no request left; subscribe first`,
    `flush() simply has to be called before expectOne(), not the other way round`,
    `The fake body must be JSON.stringify-ed first before you flush it in here`,
  ] },
  356: { answer: 1, options: [
    `Add an arbitrary setTimeout right before you assert on the DOM state here`,
    `Use autoDetectChanges() and await whenStable() before asserting on the DOM`,
    `Call detectChanges() twice in a row — the second one always catches up here`,
    `Zoneless apps just cannot be tested against the DOM; test class fields only`,
  ] },
  357: { answer: 1, options: [
    `Effects simply cannot ever run inside of a TestBed unit test environment`,
    `Effects are scheduled, not synchronous; call TestBed.tick() then assert`,
    `localStorage is read-only when you are running inside of the test harness`,
    `Signals must be declared with { effects: true } before they are observable`,
  ] },
  358: { answer: 1, options: [
    `setProperty for the first blank and fixture.autoDetect() for the second`,
    `setInput first, then detectChanges()/whenStable() — the only supported way`,
    `user.set for the first blank and TestBed.flush() for the second blank here`,
    `Direct assignment for the first blank and nothing at all for the second`,
  ] },
  359: { answer: 1, options: [
    `Harnesses run tests in a real browser, whereas CSS queries simply cannot`,
    `A stable semantic API over internal DOM; one code path for unit and e2e`,
    `They make the tests faster mainly by skipping the rendering step entirely`,
    `They are required — Material components throw when they are queried directly`,
  ] },
  360: { answer: 1, options: [
    `subscribe() is just not allowed to be used inside of an it() block here`,
    `It passes vacuously if nothing emits; use firstValueFrom so silence fails`,
    `every() is simply not allowed to be called from inside an expect() call`,
    `The subscription leaks memory, which will eventually fail the whole suite`,
  ] },
  419: { answer: 1, options: [
    `A backup copy that the Angular CLI keeps around purely for the rollbacks`,
    `The unit-test file: a describe/it suite run by ng test, next to the code`,
    `A TypeScript spec the compiler validates the component against at build`,
    `An end-to-end test that drives the whole application inside a real browser`,
  ] },
  420: { answer: 1, options: [
    `They are all Angular decorators that get registered by the TestBed for you`,
    `describe groups a suite; it is one case; expect starts an assertion`,
    `Three convenient aliases for the console.log function used within tests`,
    `Keywords that TypeScript itself only understands inside of .spec.ts files`,
  ] },
  421: { answer: 1, options: [
    `A quirk that is only kept around for backwards compatibility with AngularJS`,
    `beforeEach re-runs before every it(), giving each test a fresh fixture`,
    `Components can only ever be instantiated one single time per whole file`,
    `It caches the component so all of the tests can share one instance for speed`,
  ] },
  422: { answer: 1, options: [
    `1: Hello Ada — 2: Hello Ada, because the binding here is synchronous`,
    `1: (empty) then 2: Hello Ada — the fixture never auto-renders on its own`,
    `A runtime error, because componentInstance is read-only inside of the tests`,
    `1: Hello — 2: Hello Ada, because the static part of it renders eagerly`,
  ] },
  423: { answer: 1, options: [
    `It runs the whole test inside a Web Worker purely for the sake of isolation`,
    `Timers become a virtual clock you advance with tick(ms) — instant, no flake`,
    `It silently converts every promise into a synchronous function everywhere`,
    `It is strictly required for any test that so much as touches the HttpClient`,
  ] },
  424: { answer: 1, options: [
    `It spins up a local mock HTTP server for you, listening on the port 4200`,
    `It swaps the backend for a double: expectOne asserts, flush answers, verify`,
    `It records the real API responses a single time and then replays them forever`,
    `It makes HttpClient just return undefined so that tests skip the HTTP paths`,
  ] },
};
