/** Length-balanced option rewrites for the `routing` category.
 * Skips already-balanced #39/#50. Answer indices unchanged (#119 and #120 stay
 * 0; the rest stay 1). Depth stays in each (untouched) explanation.
 * Backtick strings — no option contains a backtick or ${ . */
export default {
  15: { answer: 1, options: [
    `null, to indicate that no decision has yet been made`,
    `true to allow, false to block, or a UrlTree to redirect`,
    `void, to indicate that the guard has finished running`,
    `An Observable that emits either true or false eventually`,
  ] },
  16: { answer: 1, options: [
    `inject() cannot be called in a function guard; use the constructor`,
    `On false it returns undefined, which Angular treats as allow`,
    `Router.navigate() is async; await it or use createUrlTree()`,
    `CanActivateFn must return an Observable, not a sync boolean`,
  ] },
  38: { answer: 1, options: [
    `Both simply block navigation to the current route with no fallback`,
    `CanMatch skips the route and tries the next; CanActivate blocks`,
    `CanMatchFn is only ever checked for lazy-loaded routes`,
    `CanActivateFn always runs before CanMatchFn is evaluated`,
  ] },
  109: { answer: 1, options: [
    `Add a second { path: } entry that carries a "/" prefix`,
    `Use children: [] on the parent, which needs a router-outlet`,
    `Nest router-outlet elements in the template with no route config`,
    `Call parentRoute.addChild(childRoute) at app runtime`,
  ] },
  110: { answer: 1, options: [
    `router.navigate(["/products/42?sort=price#reviews"])`,
    `router.navigate(["/products", 42], { queryParams, fragment })`,
    `router.navigateByUrl("/products/42", { queryParams: { sort } })`,
    `router.go("/products/42?sort=price#reviews") does it`,
  ] },
  111: { answer: 1, options: [
    `snapshot works only on first navigation; the observable on all`,
    `snapshot reads current params once; paramMap emits on changes`,
    `They are identical — use snapshot for production performance`,
    `The paramMap observable exists only in Angular 16+ builds`,
  ] },
  112: { answer: 1, options: [
    `It matches all routes and serves as the default home page`,
    `A wildcard matching any unmatched URL — must be placed LAST`,
    `It matches all routes that literally start with two asterisks`,
    `It enables regex-based route matching within the config`,
  ] },
  113: { answer: 1, options: [
    `Override ngOnInit and then call router.getCurrentNavigation()`,
    `Subscribe to router.events, filtering by the event classes`,
    `Use the window.history API to listen for popstate events`,
    `Add a RouterInterceptor to the app's providers array`,
  ] },
  114: { answer: 1, options: [
    `It adds Angular's generated attribute selector for encapsulation`,
    `It adds the "active" CSS class when the URL matches the route`,
    `It disables the link while active to prevent self-navigation`,
    `It applies only when routerLink points to an exact URL match`,
  ] },
  115: { answer: 1, options: [
    `canActivate runs first, and only then does canMatch run afterward`,
    `canMatch runs first (selection); canActivate then (activation)`,
    `They both run in parallel during the same phase`,
    `The order depends on where they appear in the route config`,
  ] },
  116: { answer: 1, options: [
    `Use a query parameter inside the URL, such as /page?title=Home`,
    `Use the route's data property, read via snapshot.data["key"]`,
    `Add a resolve function that returns a static object value`,
    `Pass it as a route path parameter, like /page/Home`,
  ] },
  117: { answer: 1, options: [
    `It creates a sidebar CSS layout beside the main outlet`,
    `A named auxiliary outlet targeted via { outlets: {...} }`,
    `It replaces the default router-outlet with a custom one`,
    `Named outlets are deprecated — use multiple primary ones`,
  ] },
  118: { answer: 1, options: [
    `Set PreloadAllModules and then use guards to skip unwanted routes`,
    `Implement PreloadingStrategy; call load() only when data says so`,
    `Add lazy: "eager" to the routes you want preloaded`,
    `Custom preloading is unsupported — only the two built-ins exist`,
  ] },
  119: { answer: 0, options: [
    `Navigates to a sibling — "../" goes up one level, then in`,
    `Navigates to the root first, then finds the "sibling" route`,
    `Navigates backwards in the browser history by one step`,
    `../ is not valid inside Angular navigation command arrays`,
  ] },
  120: { answer: 0, options: [
    `It navigates but does not update the browser's URL bar`,
    `It skips the canDeactivate guard for the current component`,
    `It replaces history instead of pushing (replaceState)`,
    `It makes navigation skip all guards and resolvers entirely`,
  ] },
  156: { answer: 1, options: [
    `{ path: "admin", component: () => import("./admin") }`,
    `{ path: "admin", loadComponent: () => import(...).then(...) }`,
    `{ path: "admin", lazy: true, component: AdminComponent } loads it`,
    `{ path: "admin", defer: () => AdminComponent } loads it`,
  ] },
  164: { answer: 1, options: [
    `ActivatedRoute is the router itself — use it to navigate`,
    `The current route; read snapshot.paramMap or subscribe to it`,
    `ActivatedRoute is only ever available in root, not lazy routes`,
    `ActivatedRoute is deprecated — use ActivatedRouteSnapshot`,
  ] },
  173: { answer: 1, options: [
    `It stops a route from activating unless a condition is met`,
    `It runs when navigating AWAY — for unsaved-changes prompts`,
    `It deactivates a route, making it inaccessible without reload`,
    `It clears route parameters when leaving the component`,
  ] },
  181: { answer: 1, options: [
    `A resolver is a guard blocking navigation by user permission`,
    `It pre-fetches data BEFORE a route activates, no loading flash`,
    `A resolver transforms route params before the component gets them`,
    `Resolvers are deprecated — use resource() in the component now`,
  ] },
  197: { answer: 1, options: [
    `It makes the router do exact URL matching for its decisions`,
    `It marks routerLinkActive only on an EXACT URL match, not prefix`,
    `It disables partial matching for the route parameters`,
    `exact: true is the default — set exact: false for prefix matching`,
  ] },
  213: { answer: 1, options: [
    `It automatically lazy-loads every routed component for you`,
    `It binds route params, query params and data to inputs by name`,
    `It validates that route params match the input types at runtime`,
    `It enables two-way binding between the URL and component state`,
  ] },
  214: { answer: 1, options: [
    `Add { provide: HTTP_INTERCEPTORS, useClass, multi: true }`,
    `provideHttpClient(withInterceptors([authInterceptor]))`,
    `Decorate the class with @Interceptor() so it auto-registers`,
    `Pass it to bootstrapApplication as its second argument`,
  ] },
  271: { answer: 1, options: [
    `It preloads every one of the lazy routes on application startup`,
    `It wraps navigations in the View Transitions API for animation`,
    `It enables server-side rendering for all of the routes`,
    `It adds a loading spinner shown between every single route change`,
  ] },
  333: { answer: 1, options: [
    `Order is irrelevant — Angular auto-picks the most specific match`,
    `First-match-wins top to bottom; the ** wildcard must go LAST`,
    `Routes are matched alphabetically by their path string`,
    `The wildcard must be first so that errors are caught early`,
  ] },
  334: { answer: 1, options: [
    `The pathMatch is decorative here and can safely be omitted`,
    `Default prefix matches every URL; "full" needs an empty rest`,
    `pathMatch: "full" makes the redirect permanent (a 301)`,
    `It enables query parameters to ride along on the redirect URL`,
  ] },
  335: { answer: 1, options: [
    `href="/products/{{ product.id }}" — plain interpolated href`,
    `[routerLink]="['/products', product.id]" — the array form`,
    `routerLink="/products/product.id" — evaluated automatically`,
    `(click)="window.location = '/products/' + product.id"`,
  ] },
  336: { answer: 1, options: [
    `href is entirely forbidden inside Angular templates`,
    `href fully reloads the app; routerLink routes client-side`,
    `routerLink is only needed for lazy-loaded routes anyway`,
    `They behave identically since both of them just render anchors`,
  ] },
  337: { answer: 1, options: [
    `It renders the routed component right INSIDE itself, like a div`,
    `A placeholder; the component renders as a SIBLING after it`,
    `It fetches the component's data before it is displayed`,
    `An app can contain only a single router-outlet, ever`,
  ] },
  338: { answer: 1, options: [
    `Query params always survive a navigation automatically`,
    `Use "preserve" to keep params, or "merge" to combine them`,
    `Store the params in localStorage and restore them manually`,
    `Use a resolver to re-fetch the params after navigating`,
  ] },
  339: { answer: 1, options: [
    `They are identical; navigateByUrl is simply the legacy one`,
    `navigate() takes a commands array; navigateByUrl() a full URL`,
    `navigate() is synchronous while navigateByUrl() returns a promise`,
    `navigateByUrl() bypasses all of the route guards entirely`,
  ] },
  340: { answer: 1, options: [
    `They are two names for the same map of the whole URL`,
    `paramMap holds path params; queryParamMap holds the ?query`,
    `queryParamMap only works with the HashLocationStrategy`,
    `paramMap contains numbers while queryParamMap holds strings`,
  ] },
  341: { answer: 1, options: [
    `Set document.title inside every component's constructor`,
    `Use the route title property, or a custom TitleStrategy`,
    `Titles can only ever be set once in the index.html file`,
    `Add a <title> element inside each component's template`,
  ] },
  342: { answer: 1, options: [
    `The Angular router is simply broken in all production builds now`,
    `The server has no such file; rewrite unknown paths to index.html`,
    `Deep links always require SSR in every possible case`,
    `You must generate a physical HTML file for each route`,
  ] },
  343: { answer: 1, options: [
    `Reuse one component class across several different route paths`,
    `Control whether a route's component is destroyed or stored`,
    `Automatically deduplicate identical HTTP requests across routes`,
    `Force every navigation to recreate all of its components`,
  ] },
  344: { answer: 1, options: [
    `Impossible — same-url navigation is always a plain no-op`,
    `onSameUrlNavigation "reload" plus runGuardsAndResolvers "always"`,
    `Just call window.location.reload() — that is the intended API here`,
    `Set every guard to return false once to force the refresh`,
  ] },
};
