/** Length-balanced option rewrites for the `forms` category.
 * Skips already-balanced #35/#108. Answer indices unchanged from current data
 * (#324 stays 0; all others stay 1). Depth lives in each (untouched) explanation.
 * Backtick strings — no option contains a backtick or ${ . */
export default {
  13: { answer: 1, options: [
    `Template-driven is faster; Reactive is the more powerful, flexible one`,
    `Template-driven derives its state from ngModel; Reactive uses FormControl`,
    `They are equivalent; teams merely prefer one form syntax over the other`,
    `Reactive forms support signals; Template-driven works only with zones here`,
  ] },
  14: { answer: 1, options: [
    `FormGroup requires FormBuilder; the direct constructor is deprecated now`,
    `form.get("email") returns AbstractControl | null; cast it to FormControl`,
    `Validators.email is not in @angular/forms; you must import it separately`,
    `The form needs an ngSubmit before change detection sees validation state`,
  ] },
  36: { answer: 1, options: [
    `setValue() does not actually exist; you must use the set() method instead`,
    `setValue() is strict — it needs every control, so omitting lastName throws`,
    `FormGroup requires a FormBuilder; the direct constructor is not supported`,
    `The object keys have to match each formControlName in the template exactly`,
  ] },
  37: { answer: 1, options: [
    `null — exactly the same as a passing synchronous validator would return`,
    `Observable<ValidationErrors | null>; status is PENDING, resolves later`,
    `A boolean: true while it is pending, or false once the check is complete`,
    `Some kind of ValidationPending sentinel object while it is still running`,
  ] },
  96: { answer: 1, options: [
    `The control's current value is reset on every single blur event fired`,
    `Validators and valueChanges fire on blur, not on each keystroke typed`,
    `The control becomes read-only right after the very first blur happens`,
    `The control marks itself touched on blur (which the default already does)`,
  ] },
  97: { answer: 1, options: [
    `Add the very same validator to each of the two FormControls individually`,
    `Add a validator to the FormGroup; it can compare the two child values`,
    `Use a custom async validator that calls the server to verify the match`,
    `Subscribe to valueChanges and manually set an error on confirmPassword`,
  ] },
  98: { answer: 1, options: [
    `getRawValue() returns the values as strings; value returns typed values`,
    `value drops disabled controls; getRawValue() includes every control`,
    `getRawValue() triggers validation to run, whereas plain value does not`,
    `They are completely identical in every modern version of Angular today`,
  ] },
  99: { answer: 1, options: [
    `It resets every control to its initial value and then marks them all pristine`,
    `It recursively marks every control in the group touched, revealing errors`,
    `It triggers the async validators on all of the controls simultaneously`,
    `It is basically equivalent to calling patchValue({}) on the whole group`,
  ] },
  100: { answer: 1, options: [
    `It prevents any null values from ever being submitted to the server here`,
    `Controls reset to their initial value, not null, when reset() is called`,
    `It adds a Validators.required validator onto every one of the controls`,
    `It makes each control read-only so their values cannot be set to null`,
  ] },
  101: { answer: 1, options: [
    `map() is not allowed to return null here — you must use filter() instead`,
    `Fast typing overlaps requests; a stale response can win — use switchMap`,
    `The validator must return Observable<ValidationErrors | null>, not this`,
    `Async validators are required to return a Promise, never an Observable`,
  ] },
  102: { answer: 1, options: [
    `Subscribe to every single FormControl's valueChanges individually here`,
    `Subscribe to form.valueChanges; it emits the value object on any change`,
    `Use the (ngModelChange) event directly on the form tag in the template`,
    `Override ngOnChanges and inspect the whole form as a SimpleChange object`,
  ] },
  103: { answer: 1, options: [
    `The three are setValue(), getValue(), and validate() on the accessor`,
    `writeValue(), registerOnChange(), registerOnTouched() (plus disabled)`,
    `They are ngModelChange(), ngModelWrite(), and ngModelDisable() methods`,
    `The three are simply onChange(), onTouch(), and onDisable() by name here`,
  ] },
  104: { answer: 1, options: [
    `It emits the validation errors object each time that validation fails`,
    `It emits VALID, INVALID or PENDING whenever the control's status changes`,
    `It emits the total number of currently failed validators, as a count`,
    `It only emits when a control moves from VALID straight to the INVALID state`,
  ] },
  105: { answer: 1, options: [
    `It automatically adds a Validators.required validator to all of the fields`,
    `form.value and control.value are fully typed; typos are caught at compile`,
    `It enables two-way binding between a FormGroup and an interface directly`,
    `Typed forms will automatically serialize themselves to JSON for a server`,
  ] },
  106: { answer: 1, options: [
    `Assign it: this.form.controls["newField"] = new FormControl("") directly here`,
    `Call this.form.addControl("newField", new FormControl("")) to register it`,
    `Call this.form.push(new FormControl("")) to add the new field to it here`,
    `Use this.form.patch({ newField: new FormControl("") }) to add it in here`,
  ] },
  107: { answer: 1, options: [
    `setValue() triggers validation while patchValue() bypasses all validators`,
    `setValue() needs every key or it throws; patchValue() updates only some`,
    `patchValue() works only on a FormArray while setValue() is for a FormGroup`,
    `They are entirely identical in both their behaviour and their output here`,
  ] },
  157: { answer: 1, options: [
    `compose() runs the validators in parallel; an array runs them one by one`,
    `They are identical; compose() just merges the validators into one fn`,
    `compose() short-circuits on the first error; an array always runs them all`,
    `compose() only works for the async validators, never the synchronous ones`,
  ] },
  167: { answer: 1, options: [
    `It binds the form's submit event straight to the myForm method for you`,
    `It links the form to a FormGroup so child directives can resolve controls`,
    `It imports the FormGroup class directly into the template for you to use here`,
    `It automatically calls myForm.reset() every time the form is submitted`,
  ] },
  177: { answer: 1, options: [
    `FormArray holds primitive values like strings — a multi-value FormControl`,
    `FormArray manages an ordered, dynamic list of controls you add or remove`,
    `FormArray is a deprecated alternative to FormGroup for the flat forms here`,
    `FormArray binds to a <select multiple> element for multi-value selection`,
  ] },
  194: { answer: 1, options: [
    `dirty means that validation failed, while touched means the user interacted`,
    `dirty means the value changed; touched means it was focused then blurred`,
    `They are identical — both turn true the moment the user types in a field`,
    `dirty tracks async validation state while touched tracks sync validation`,
  ] },
  196: { answer: 1, options: [
    `You simply cannot check form.valid synchronously the way this code does`,
    `Disabled controls are dropped from form.value; use getRawValue() instead`,
    `The save() call really ought to be wrapped inside a try/catch block here`,
    `You must call form.markAllAsTouched() before you check form.valid at all`,
  ] },
  204: { answer: 1, options: [
    `reset() is deprecated now; use clear(), which will preserve the type here`,
    `A default control is nullable; reset() yields null — use { nonNullable }`,
    `FormControl values are always strings; the error is unrelated to reset()`,
    `You must pass an empty string: reset(""), but the type stays nullable still`,
  ] },
  205: { answer: 1, options: [
    `It disables the control entirely until the user first focuses into it`,
    `Value and validity update on blur, not each keystroke, reducing churn`,
    `It debounces the control's value changes by a fixed 300ms delay instead`,
    `It makes the control update on every change AND on blur, whichever is first`,
  ] },
  245: { answer: 1, options: [
    `ngModel is deprecated now; you are required to use a Reactive FormControl`,
    `Two-way [(ngModel)] needs FormsModule — add it to the imports array here`,
    `The name field must be declared as a signal for ngModel to work at all`,
    `[(ngModel)] must be split into [ngModel] with a separate (ngModelChange)`,
  ] },
  321: { answer: 1, options: [
    `A special compiler mode that has no equivalent longhand form at all here`,
    `[ngModel]="name" plus (ngModelChange)="name = value" — input and output`,
    `A two-way binding straight to the DOM element's value attribute directly`,
    `A shortcut that creates a FormControl behind the scenes in reactive forms`,
  ] },
  322: { answer: 1, options: [
    `Immediately on page load, so that users know all of the rules upfront`,
    `Once the control is touched or dirty — earlier just reads as nagging`,
    `Only after the entire form has already been submitted successfully once`,
    `Never — invalid controls really should just be silently ignored entirely`,
  ] },
  323: { answer: 1, options: [
    `Bind [disabled]="isDisabled" on the input just like any other property`,
    `Use the API: { value: "", disabled: true } or control.disable()/enable()`,
    `Just set control.readonly = true on the control and leave it at that here`,
    `Remove the control from the FormGroup entirely to disable it for the user`,
  ] },
  324: { answer: 0, options: [
    `FormControl, FormGroup, FormArray — one value, a keyed object, a list`,
    `Input, Form, Button — the three HTML elements that Angular enhances here`,
    `Model, View, Controller — the classic MVC triad applied here onto forms`,
    `ngModel, ngForm, ngSubmit — the three main reactive forms directives here`,
  ] },
  325: { answer: 1, options: [
    `Only a single validator is ever allowed per control in reactive forms`,
    `Pass an array: [Validators.required, Validators.email] — errors merge`,
    `Chain them fluently like Validators.required.email.minLength(8) instead`,
    `Write them purely as HTML attributes only, such as required minlength=8`,
  ] },
  326: { answer: 1, options: [
    `ngSubmit is required here, or else Angular throws a runtime error at you`,
    `ngSubmit fires on click AND Enter, and prevents the default page reload`,
    `A click handler is simply unable to call any component methods at all here`,
    `ngSubmit automatically validates the form and blocks invalid ones for you`,
  ] },
  327: { answer: 1, options: [
    `Use form.address.street — the controls become properties on the group`,
    `form.get("address.street") — get() walks the nested groups and arrays`,
    `Call form.find("street"), which searches every level of the form by name`,
    `Nested FormGroups are not supported at all, so flatten the whole form out`,
  ] },
  328: { answer: 1, options: [
    `Call the API directly in (keyup) — the very simplest option is best here`,
    `valueChanges.pipe(debounceTime, distinctUntilChanged, switchMap) does it`,
    `Poll the API once every second and then filter the results client-side`,
    `valueChanges.pipe(mergeMap(...)) so every keystroke's request completes`,
  ] },
  329: { answer: 1, options: [
    `control.value.includes(" ") — just returning a boolean pass or fail value`,
    `control.value?.includes(" ") ? { noSpaces: true } : null — errors or null`,
    `throw new ValidationError("spaces") from the validator whenever invalid`,
    `control.setErrors({ noSpaces: true }) and then return nothing at all here`,
  ] },
  330: { answer: 1, options: [
    `They are freely interchangeable in absolutely any context you use them`,
    `formControlName is a string key under a parent group; [formControl] a ref`,
    `[formControl] is deprecated now, in favor of using formControlName instead`,
    `formControlName creates the control, while [formControl] only ever reads it`,
  ] },
  331: { answer: 1, options: [
    `It works fine — ngModel and formControlName just sync up automatically`,
    `Mixing ngModel with reactive directives is unsupported; pick one system`,
    `ngModel silently wins the conflict and the FormControl is quietly detached`,
    `It only actually breaks in the case where the form is submitted twice over`,
  ] },
  332: { answer: 1, options: [
    `Nothing at all — control.events is merely an alias for valueChanges here`,
    `One typed stream of ALL events, including touched and pristine changes`,
    `It replaces the form's validators with plain event handlers on the control`,
    `Synchronous access to future values even before the user has typed them in`,
  ] },
};
